# Cirrus CI configuration
# https://cirrus-ci.com/github/dfandrich/gpscorrelate

task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0
      image_family: freebsd-12-2

  env:
    # Set to 10 instead of 1 to avoid problems when new commits are submitted
    # during a run.
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3 -DENABLE_NLS=1
    LDFLAGS: $CFLAGS -lintl
    CC: cc
    CXX: c++
    MAKE_FLAGS: -j 2
    matrix:
      - GTK: 2
      - GTK: 3

  pkginstall_script:
    # pkg install sometimes gets package size mismatches without this
    - pkg update -f
    - pkg install -y pkgconf docbook-xsl exiv2 libxml2 gtk"$GTK" libxslt gettext-tools desktop-file-utils

  compile_script:
    # GTK3 and GTK2 on 13.0 throws up some deprecation warnings, so disable them for -Werror
    - make CC="$CC" CXX="$CXX" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" GTK="$GTK"

  test_script:
    - ./gpscorrelate -V
    # The tests involving writing to read-only files fail when run as root
    # (because the OS allows the files to be overwritten then). Run the
    # tests as a normal user to get around that problem. The log directory
    # must be world-writable since files will be written there.
    - install -d -m 0777 tests/log
    - sudo -u nobody make check CHECK_OPTIONS=-v

  install_script:
    - make prefix= DESTDIR="${HOME}" install install-po install-desktop-file
