# Travis CI configuration file
# https://travis-ci.org/dfandrich/gpscorrelate

sudo: false

language: cpp

git:
  # Set to 10 instead of 1 to avoid problems when the most recent commits have [skip ci]
  depth: 10

# Install needed packages on Ubuntu and OS X
addons:
  apt:
    packages:
      - desktop-file-utils
      - docbook-xsl
      - exiv2
      - libexiv2-dev
      - libgtk2.0-dev
      - xsltproc
    config:
      retries: true

install:
  - |
    if [ "$CONFIG" = "musl" ] ; then
      echo > Dockerfile "
        FROM alpine
        RUN apk add --no-cache build-base exiv2-dev libxml2-dev gettext-dev gtk+2.0-dev desktop-file-utils
        # Use the same user id as the one building this container
        RUN adduser -D -u $(id -u) build
      "
      docker build -t alpine-build .
    fi

env:
  global:
    - MAKEFLAGS='-j 2'

matrix:
  include:
  - env: CONFIG=musl DIST=alpine
    os: linux
    sudo: required
    services: docker
  - env: CONFIG=normal DIST=bionic
    arch: arm64
    os: linux
    dist: bionic
    compiler: gcc
  - env: CONFIG=normal DIST=focal
    arch: arm64
    os: linux
    dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
          - desktop-file-utils
          - docbook-xsl
          - exiv2
          - gettext
          - libexiv2-dev
          - libgtk2.0-dev
          - xsltproc
        config:
          retries: true
  - env: CONFIG=normal DIST=bionic GTK=3
    arch: ppc64le
    os: linux
    dist: bionic
    compiler: gcc
  - env: CONFIG=normal DIST=focal GTK=3
    arch: ppc64le
    os: linux
    dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
          - desktop-file-utils
          - docbook-xsl
          - exiv2
          - gettext
          - libexiv2-dev
          - libgtk-3-dev
          - xsltproc
        config:
          retries: true

before_install:
  - GTK=${GTK:-2}
  # The apt addons section is ignored on bionic for some reason
  - if [ "${DIST}" = "bionic" ] ; then travis_retry sudo apt-get install -y desktop-file-utils docbook-xsl exiv2 gettext libexiv2-dev libgtk${GTK/3/-}${GTK/2/.0}-dev libxml2-dev xsltproc; fi

script:
  # Build everything by default
  - TARGET='all'
  - INSTALLTARGET='install install-po install-desktop-file'
  - if [ "$CONFIG" = "normal" ] ; then CFLAGS='-Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3 -DENABLE_NLS=1'; fi

  - |
    set -e
    if [ "$CONFIG" = "musl" ] ; then
      # Some tests fail if run as root (the ones to do with read only files)
      # so run as another user.
      docker run --user $(id -u) --rm -v "$PWD":/tmp/src alpine-build sh -c '
        cat /etc/os-release
        set -ex
        cd /tmp/src
        make CFLAGS=-DENABLE_NLS LDFLAGS=-lintl GTK=2 gpscorrelate gpscorrelate-gui
        ./gpscorrelate -V
        make check
        make install-po install-desktop-file prefix= DESTDIR="\${HOME}"
        '
    else
      make CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" CC="$CC" CXX="$CXX" GTK="$GTK" $MAKE_OPTS $TARGET
     ./gpscorrelate -V
      make check CHECK_OPTIONS=-v
      # Mac OS needs this or else it will sometimes rebuild the binary on install
      sleep 5
      # Ensure brew gettext is in the PATH so xgettext is found on OS X
      PATH="$PATH:/usr/local/opt/gettext/bin" make prefix= DESTDIR="${HOME}" $INSTALLTARGET
    fi
    set +e
